langguage: go

  go:
    - master
  install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.60.1/hugo_0.60.1_Linux-64bit.tar.gz
    - tar -zxf hugo_0.60.1_Linux-64bit.tar.gz
    - chmod a+x hugo

  script:
    - ./hugo

  deploy:
    provider: pages
    skip_cleanup: true
    github_token: 287714e3a85a6bfd1b05991b295b4863abafa79a
    on:
      branch: notebackup
    local_dir: ./public
    repo: No-SKy/no-sky.github.io
    email: nosky_xfw@163.com
    target_branch: master