baseURL = "https://no-sky.github.io"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Note"              # 网站标题
theme = "leavelt"

paginate = 10
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "UA-135962328-2"

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"


 [menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

#  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[params]
    since = 2016
    author = "nosky"                           # Author's name
    avatar = "/images/avatar.png"           # Author's avatar
    subtitle = "路漫漫其修远兮，吾将上下而求索"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "nosky 的个人学习笔记" # site description
    keywords = ["note", "笔记","nosky"] # site keywords

    beian = "湘ICP备19027112号"
    policeBeian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.social]
    GitHub = "no-sky"
    Twitter = ""
    Email   = "mailto:nosky@xiaofangwei.cn"
    Instagram = ""
    Wechat = ""  # Wechat QRcode image
    Facebook = ""
    Telegram = ""
    Dribbble = ""
    Medium = ""
