name: CI #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - notebackup
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
      - name: checkout # 步骤的名称
        uses: actions/checkout@master #软件市场的名称
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.60.1'
          extended: true
      - name: Build
        run: hugo --gc
      - name: Deploy
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
          SCRIPT_MODE: true
        run: |
          cd /public

          mkdir -p ~/.ssh/

          echo "$ACCESS_TOKEN" | tr -d '\r' > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # set git infomation
          git init

          git config --global user.name 'xiaofangwei'

          git config --global user.email 'nosky.xfw@outlook.com'

          git remote add origin git@github.com:no-sky/no-sky.github.io.git

          git add .

          git commit -m "CI"

          git push origin master -f

