name: Build and Update Github Pages

on: 
  push:
    branches:    
      - notebackup

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

   
      - name: Setup Hugo

        uses: peaceiris/actions-hugo@v2

        with:
          hugo-version: '0.59.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.HUGO_TOKE }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: /